[build]
base = "www"
command = "pnpm install --production=false && pnpm build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from     = "/"
to       = "/convert"
status   = 301
force    = true

[build.environment]
NODE_ENV = "production"
